"$schema" = "./node_modules/wrangler/config-schema.json"
name = "cryptdowner"
main = "backend/index.js"
compatibility_date = "2026-02-10"
workers_dev = true
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "src"
binding = "ASSETS"

[build]
command = ""

[route]
pattern = "cryptdowner.daedalist.net/*"
zone_name = "daedalist.net"

[[kv_namespaces]]
binding = "cryptdowner"
id = "6751422c4e08453c964f2774e396d267"

[env.staging]
name = "cryptdowner-staging"

[[ratelimits]]
name = "RATE_LIMITER"
namespace_id = "1001"

  [ratelimits.simple]
  limit = 5
  period = 60

[[ratelimits]]
name = "READ_RATE_LIMITER"
namespace_id = "1001"

  [ratelimits.simple]
  limit = 100
  period = 60
